#!/usr/bin/env python3
"""
Quick setup helper for Plex Toolbox
This script helps you configure your .env file interactively
"""
import os
import sys
from pathlib import Path
from urllib.parse import quote_plus

# Get the backend directory
BACKEND_DIR = Path(__file__).parent
ENV_FILE = BACKEND_DIR / ".env"


def encode_password(password: str) -> str:
    """Encode password for URL"""
    return quote_plus(password)


def main():
    print("=" * 60)
    print("Plex Toolbox - Database Configuration Helper")
    print("=" * 60)
    print()
    
    # Check if .env exists
    if ENV_FILE.exists():
        print(f"✅ .env file exists at: {ENV_FILE}")
        response = input("Do you want to reconfigure it? (y/n): ")
        if response.lower() not in ['y', 'yes']:
            print("Keeping existing configuration.")
            return
    else:
        print("❌ .env file not found")
        print("Starting configuration wizard...")
        print()
    
    # Ask about database type
    print("Which database do you want to use?")
    print("1. SQLite (Simple, for development/testing)")
    print("2. PostgreSQL/TimescaleDB (Production)")
    print()
    
    while True:
        choice = input("Enter choice (1 or 2): ").strip()
        if choice in ['1', '2']:
            break
        print("Invalid choice. Please enter 1 or 2.")
    
    if choice == '1':
        # SQLite
        database_url = "sqlite:///./plex_toolbox.db"
        print()
        print("✅ Using SQLite")
        print(f"   Database file: ./plex_toolbox.db")
    else:
        # PostgreSQL
        print()
        print("PostgreSQL/TimescaleDB Configuration")
        print("-" * 40)
        
        host = input("Database host (e.g., 192.168.1.100): ").strip()
        port = input("Database port [5432]: ").strip() or "5432"
        database = input("Database name [plex_toolbox]: ").strip() or "plex_toolbox"
        username = input("Username [plextoolbox]: ").strip() or "plextoolbox"
        password = input("Password: ").strip()
        
        # Encode password to handle special characters
        encoded_password = encode_password(password)
        
        # Check if encoding was needed
        if encoded_password != password:
            print()
            print("ℹ️  Password contains special characters - auto-encoded for URL")
            print(f"   Original:  {password}")
            print(f"   Encoded:   {encoded_password}")
        
        database_url = f"postgresql://{username}:{encoded_password}@{host}:{port}/{database}"
        print()
        print("✅ Database configuration:")
        print(f"   Host: {host}")
        print(f"   Port: {port}")
        print(f"   Database: {database}")
        print(f"   Username: {username}")
    
    # Create .env content
    env_content = f"""# Plex Toolbox Environment Configuration
# Generated by setup helper

# Database Configuration
DATABASE_URL={database_url}

# Application Settings
ENVIRONMENT=development
PROJECT_NAME=Plex Toolbox

# Security (auto-generated on first startup)
SECRET_KEY=change-this-to-a-random-secret-key-in-production
ACCESS_TOKEN_EXPIRE_MINUTES=10080

# CORS Settings
BACKEND_CORS_ORIGINS=["http://localhost:3000","http://localhost:8000"]
"""
    
    # Write .env file
    with open(ENV_FILE, 'w') as f:
        f.write(env_content)
    
    print()
    print("=" * 60)
    print(f"✅ Configuration saved to: {ENV_FILE}")
    print()
    print("Next steps:")
    print("1. Review the .env file if needed")
    print("2. Start the backend: python -m uvicorn app.main:app --reload")
    print("3. The SECRET_KEY will be auto-generated on first startup")
    print()
    print("Note: If you need to manually encode passwords later, use:")
    print("  python -m app.core.url_encoder")
    print("=" * 60)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nConfiguration cancelled.")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ Error: {e}")
        sys.exit(1)
